services:
  api:
    build: .
    container_name: nest-api

    networks:
      - web

    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"

      # Router
      - "traefik.http.routers.demoapi.rule=Host(`demoapi.aclcodesolutions.com`)"
      - "traefik.http.routers.demoapi.entrypoints=websecure"
      - "traefik.http.routers.demoapi.tls.certresolver=le"

      # Service
      - "traefik.http.services.demoapi.loadbalancer.server.port=3000"

    env_file:
      - .env

    volumes:
      - sqlite_data:/app/data

    restart: unless-stopped

volumes:
  sqlite_data:

networks:
  web:
    external: true